//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskProject_Purus.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.CustomerDetails = new HashSet<CustomerDetail>();
        }
    
        public int QuoteID { get; set; }
        public string QuoteTtile { get; set; }
        public string QuoteDescription { get; set; }
    
        public virtual ICollection<CustomerDetail> CustomerDetails { get; set; }
    }
}
